/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  webSidebar: [
    { type: 'doc', id: 'community/quick-start', label: 'Quick Start', },
    // { type: 'doc', id: 'docs/user-guide/README', label: 'User Guide', },

    {
      type: 'category',
      collapsed: false,
      label: 'Ecosystem Evaluation System',
      link: {
        type: 'generated-index',
        description: 'Ecosystem is used to describe the health status of open source community standing from ecology context. We create a three-dimensional space for the evaluation system, including the open source ecosystem, "collaboration, people, software" and evaluation models.',
        slug: '/dimensions-define',
        keywords: ['Metrics Models Dimensions', 'Productivity', 'Robustness', 'Niche-Creation',],
        image: '/img/docusaurus.png',
      },
      items: [
        { type: 'doc', id: 'docs/metrics-models/metrics-models-overview' },

        {
          type: 'category',
          collapsed: false,
          label: 'Collaboration-Productivity',
          link: {
            type: 'generated-index',
            description: 'The efficiency with which an ecosystem or project converts inputs into output.',
            // slug: '/metrics-models/productivity',
            keywords: [],
            image: '/img/docusaurus.png',
          },
          items: [
            { type: 'doc', id: 'docs/metrics-models/collaboration/productivity/collaboration-productivity-overview' },
            { type: 'doc', id: 'docs/metrics-models/collaboration/productivity/collaboration-development-index' },
            { type: 'doc', id: 'docs/metrics-models/collaboration/productivity/community-service-and-support' },
          ],
        },

        {
          type: 'category',
          collapsed: false,
          label: 'Collaboration-Robustness',
          link: {
            type: 'generated-index',
            description: 'The capability of an ecosystem or project to face and survive disruptions.',
            slug: '/metrics-models/robustness',
            keywords: [],
            image: '/img/docusaurus.png',
          },
          items: [
            { type: 'doc', id: 'docs/metrics-models/collaboration/robustness/collaboration-robustness-overview' },
            { type: 'doc', id: 'docs/metrics-models/collaboration/robustness/activity' },
          ],
        },

        {
          type: 'category',
          collapsed: false,
          label: 'Collaboration-Niche Creation',
          link: {
            type: 'generated-index',
            description: 'The capacity to create and recognize meaningful diversity and thereby new capabilities.',
            slug: '/metrics-models/niche-creation',
            keywords: [],
            image: '/img/docusaurus.png',
          },
          items: [
            { type: 'doc', id: 'docs/metrics-models/collaboration/niche-creation/collaboration-niche-creation-overview' },
            { type: 'doc', id: 'docs/metrics-models/collaboration/niche-creation/organization-activity' },
          ],
        },

        {
          type: 'category',
          collapsed: false,
          label: 'People-Productivity',
          link: {
            type: 'generated-index',
            description: 'The efficiency with which an ecosystem or project converts inputs into output.',
            // slug: '/metrics-models/productivity',
            keywords: [],
            image: '/img/docusaurus.png',
          },
          items: [
            { type: 'doc', id: 'docs/metrics-models/people/productivity/people-productivity-overview' },
            { type: 'doc', id: 'docs/metrics-models/people/productivity/contributor-domain-persona' },
            { type: 'doc', id: 'docs/metrics-models/people/productivity/contributor-role-persona' },
            { type: 'doc', id: 'docs/metrics-models/people/productivity/contributor-milestone-persona' },
          ],
        },
        {
          type: 'category',
          collapsed: false,
          label: 'Software Artifact-Robustness',
          link: {
            type: 'generated-index',
            description: 'The efficiency with which an ecosystem or project converts inputs into output.',
            // slug: '/metrics-models/productivity',
            keywords: [],
            image: '/img/docusaurus.png',
          },
          items: [
            { type: 'doc', id: 'docs/metrics-models/software_artifact/robustness/software-artifact-robustness-overview' },
            { type: 'doc', id: 'docs/metrics-models/software_artifact/robustness/cii_best_badge' },
            { type: 'doc', id: 'docs/metrics-models/software_artifact/robustness/criticality_score' },
            { type: 'doc', id: 'docs/metrics-models/software_artifact/robustness/scorecard' },
          ],
        },
      ],
    },

    {
      type: 'category',
      collapsed: false,
      label: 'Community',
      link: {
        type: 'generated-index',
        description: 'Join the OSS-Compass Community',
        slug: '/community',
        keywords: [],
        image: '/img/docusaurus.png',
      },
      items: [
        { type: 'link', label: 'GitHub', href: 'https://github.com/oss-compass' },
        { type: 'link', label: 'Gitee', href: 'https://gitee.com/oss-compass' },
        { type: 'doc', label: 'Weekly Meeting', id: 'community/community/metting' },
        { type: 'doc', label: 'Slack', id: 'community/community/slack' },
        { type: 'doc', label: 'WeChat', id: 'community/community/wechat' },
      ],
    },

    { type: 'doc', label: 'Participating Contribution', id: 'community/CONTRIBUTING' },

    {
      type: 'category',
      collapsed: false,
      label: 'Legal',
      link: {
        type: 'generated-index',
        slug: '/legal',
        keywords: [],
        image: '/img/docusaurus.png',
      },
      items: [
        { type: 'doc', label: 'Terms', id: 'community/legal/terms-of-use' },
        { type: 'doc', label: 'Privacy', id: 'community/legal/privacy-policy' },
      ],
    },

  ],
};

module.exports = sidebars;
