name: Publish image

on:
  push:
    branches:
      - 'release'
      - 'main'

jobs:
  publish-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/

      - run: yarn install --frozen-lockfile # optional, --immutable
      - run: yarn copy
      - run: yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            build

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            osscompassorg/compass-docs
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'release') }}
            type=raw,value=nightly,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha,prefix={{branch}}-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: '${{ secrets.DOCKER_REGISTRY_USERNAME }}'
          password: '${{ secrets.DOCKER_REGISTRY_PASSWORD }}'

      - name: docker build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: GIT_COMMIT=${{ github.sha }}
